# Summary

https://pytorch.org/docs/stable/tensors.html

## dtype

| Data type | dtype |
| --- | --- |
| 16-bit floating point | `torch.float16` or `torch.half` |
| 32-bit floating point | `torch.float32` or `torch.float` |
| 64-bit floating point | `torch.float64` or `torch.double` |
| 16-bit integer | `torch.int16` or `torch.short` |
| 32-bit integer | `torch.int32` or `torch.int` |
| 64-bit integer | `torch.int64` or `torch.long` |

## tensor class or tensor type

| Data type | tensor class |
| --- | --- |
| 16-bit floating point | `torch.HalfTensor` |
| 32-bit floating point | `torch.FloatTensor` |
| 64-bit floating point | `torch.DoubleTensor` |
| 16-bit integer | `torch.ShortTensor` |
| 32-bit integer | `torch.IntTensor` |
| 64-bit integer | `torch.LongTensor` |

## tensor creation

In [ ]:
torch.FloatTensor([1.0, 2.0, 3.0])
torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)
torch.tensor([1.0, 2.0, 3.0]).to(torch.float32)
torch.tensor([1.0, 2.0, 3.0]).to(torch.float)
torch.tensor([1.0, 2.0, 3.0]).float()
# torch.tensor([1.0, 2.0, 3.0]).float32()  # AttributeError: 'Tensor' object has no attribute 'float32'

short, int, long, half, double tensor creation is similar to float tensor creation.

## recommended tensor creation

Recommended tensor creation is    

In [ ]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32, device=device)

Not recommended tensor creations are

In [ ]:
torch.tensor([1.0, 2.0, 3.0]).to(torch.float32).to(device)
torch.FloatTensor([1.0, 2.0, 3.0]).to(device)

because these are not memory efficient.

# With code

In [1]:
import torch
print(torch.__version__)

2.4.0


In [2]:
# Get cuda or mps device
if torch.cuda.is_available():
    device = torch.device('cuda')
elif torch.backends.mps.is_available():
    device = torch.device('mps')
else:
    device = torch.device('cpu')
    
print(device)

mps


## About tensor itself

In [3]:
print(torch.Tensor)
print(type(torch.Tensor))
print(torch.tensor)
print(type(torch.tensor))

<class 'torch.Tensor'>
<class 'torch._C._TensorMeta'>
<built-in method tensor of type object at 0x1222c0c68>
<class 'builtin_function_or_method'>


- `torch.Tensor` is a class of tensor objects, namely tpye of tensor, which is an alias for the default tensor class (`torch.FloatTensor`).
- `torch.tensor` is a function that returns a `torch.Tensor` object. 

## Data type and tensor type

In [4]:
print(type(torch.FloatTensor))
print(type(torch.float))

<class 'torch.tensortype'>
<class 'torch.dtype'>


- `torch.FloatTensor` is a tensor type.
- `torch.float` is a data type, which is an alias for `torch.float32`.

## Default tensor

In [5]:
x = torch.Tensor([2, 3])
print(x)
print(type(x))
print(x.dtype)

tensor([2., 3.])
<class 'torch.Tensor'>
torch.float32


In [6]:
x = torch.tensor([2, 3])
print(x)
print(type(x))
print(x.dtype)

tensor([2, 3])
<class 'torch.Tensor'>
torch.int64


In [7]:
x = torch.tensor([2., 3.])
print(x)
print(type(x))
print(x.dtype)

tensor([2., 3.])
<class 'torch.Tensor'>
torch.float32


- `torch.Tensor` is an alias for the default tensor class (`torch.FloatTensor`). So, dtype of output tensor is `torch.float32`.
- `torch.tensor` is a factory function that returns a `torch.Tensor` object. So, dtype of output tensor is determined by the input data.

## Float32(=float) tensor

In [8]:
x = torch.FloatTensor([2, 3])
print(x.dtype)

torch.float32


In [9]:
x = torch.tensor([2, 3], dtype=torch.float)
print(x.dtype)

torch.float32


In [10]:
x = torch.tensor([2, 3], dtype=torch.float32)
print(x.dtype)

torch.float32


# Float64(=double) tensor

In [11]:
x = torch.DoubleTensor([2, 3])
print(x.dtype)

torch.float64


In [12]:
x = torch.tensor([2, 3], dtype=torch.double)
print(x.dtype)

torch.float64


In [13]:
x = torch.tensor([2, 3], dtype=torch.float64)
print(x.dtype)

torch.float64


## Int32(=int) tensor

In [14]:
x = torch.IntTensor([2, 3])
print(x.dtype)

torch.int32


In [15]:
x = torch.tensor([2, 3], dtype=torch.int)
print(x.dtype)

torch.int32


In [16]:
x = torch.tensor([2, 3], dtype=torch.int32)
print(x.dtype)

torch.int32


## Int64(=long) tensor

In [17]:
x = torch.LongTensor([2, 3])
print(x.dtype)

torch.int64


In [18]:
x = torch.tensor([2, 3], dtype=torch.long)
print(x.dtype)

torch.int64


In [19]:
x = torch.tensor([2, 3], dtype=torch.int64)
print(x.dtype)

torch.int64


## Convert tensor dtype

In [20]:
print(torch.tensor([2, 3]).to(torch.int).dtype)
print(torch.tensor([2, 3]).to(torch.long).dtype)
print(torch.tensor([2, 3]).to(torch.float).dtype)
print(torch.tensor([2, 3]).to(torch.double).dtype)

torch.int32
torch.int64
torch.float32
torch.float64


In [21]:
print(torch.tensor([2, 3]).to(torch.int32).dtype)
print(torch.tensor([2, 3]).to(torch.int64).dtype)
print(torch.tensor([2, 3]).to(torch.float32).dtype)
print(torch.tensor([2, 3]).to(torch.float64).dtype)

torch.int32
torch.int64
torch.float32
torch.float64


In [22]:
print(torch.tensor([2, 3]).int().dtype)
print(torch.tensor([2, 3]).long().dtype)
print(torch.tensor([2, 3]).float().dtype)
print(torch.tensor([2, 3]).double().dtype)

torch.int32
torch.int64
torch.float32
torch.float64


In [23]:
print(torch.tensor([2, 3]).int32().dtype)
print(torch.tensor([2, 3]).int64().dtype)
print(torch.tensor([2, 3]).float32().dtype)
print(torch.tensor([2, 3]).float64().dtype)
"""
AttributeError: 'Tensor' object has no attribute 'int32', 'int64', 'float32', 'float64'
"""

AttributeError: 'Tensor' object has no attribute 'int32'

***